Sneakers_proj/Sneakers_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sneakers_app.urls'))
]

Sneakers_proj/sneakers_app/urls.py
from django.urls import URLPattern, path
from . import views


app_name = 'sneakers_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.user_logout, name='logout'),
    path('favorite/', views.favorite, name='favorite'),
    path('favorite/<int:id>', views.favorite_detail,
         name='favorite_page_detail'),
]

Sneakers_proj/sneakers_app/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone

# Create your models here.


class favoriteShoe(models.Model):
    name = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    releaseDate = models.DateField(blank=True)
    retailPrice = models.IntegerField()
    flightClub = models.CharField(max_length=300)
    goat = models.CharField(max_length=300)
    # image = models.ImageField(upload_to=None,)

    def __str__(self):
        return f'{self.name} {self.brand} {self.releaseDate} {self.retailPrice}'

Sneakers_proj/sneakers_app/forms.py
from django import forms


class NewSignUpForm(forms.Form):
    username = forms.CharField(
        label='Username', widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(
        label='First Name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(
        label='Last Name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(
        attrs={'class': 'form-control'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password', max_length=10)


class NewLoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='password', max_length=10)

Sneakers_proj/sneakers_app/views.py
from logging import exception
from urllib import response
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import requests as fetch
from .models import *
from .forms import *
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.http import JsonResponse
from .serializers import *
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

# Create your views here.
# test


def index(request):
    return render(request, 'sneakers_app/index.html')


def user_login(request):
    if request.method == 'GET':
        form2 = NewLoginForm()
        return render(request, 'sneakers_app/login.html', {
            'form2': form2
        })

    elif request.method == 'POST':
        form2 = NewLoginForm(request.POST)
        if form2.is_valid():
            password = form2.cleaned_data['password']
            user = authenticate(
                request, username=form2.cleaned_data['username'], password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('sneakers_app:profile'))
            else:
                form2.add_error('username', 'Invalid Login')
                return render(request, 'sneakers_app/login.html', {'form2': form2})


def register(request):
    if request.method == 'GET':
        form = NewSignUpForm()
        return render(request, 'sneakers_app/register.html', {
            'form': form,
        })
    elif request.method == 'POST':
        form = NewSignUpForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password'],
            )
        return HttpResponseRedirect(reverse('sneakers_app:user_login'))


def profile(request):
    person = User.objects.all()
    context = {
        'person': person
    }
    return render(request, 'sneakers_app/profile.html', context)


# # logout function
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('sneakers_app:user_login'))


@api_view(['GET', 'POST'])
def favorite(request):
    if request.method == 'GET':
        shoe = favoriteShoe.objects.all()
        serializer = sneaksSerializer(shoe, many=True)
        return Response(serializer.data)

    if request.method == 'POST':
        serializer = sneaksSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)


@api_view(['GET', 'PUT', 'DELETE'])
def favorite_detail(request, id):
    try:
        shoe = favoriteShoe.objects.get(pk=id)
    except favoriteShoe.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = sneaksSerializer(shoe)
        return Response(serializer.data)
    elif request.method == 'PUT':
        serializer = sneaksSerializer(shoe, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.error, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        shoe.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

Sneakers_proj/sneakers_app/templates/sneakers_app/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Koulen&display=swap"
      rel="stylesheet"
    />
    <!-- Link to CSS File -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'sneakers_app/css/style.css' %}"
    />
    <!-- Link to JS File -->
    <script defer src="{% static 'sneakers_app/js/app.js' %}"></script>
    <!-- favicon -->
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'sneakers_app/images/Sneaks.jpg' %}"
    />
    <!-- VUE -->

    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>

    <title>Sneaks</title>
  </head>
  <body>

    <!-- enter -->
    <div id="app">
      <div class="container-fluid">
        <div class="row flex-nowrap">
          <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div
              class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
            >
              <ul
                class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
                id="menu"
              >
                <li class="nav-item">
                  <a
                    href="{% url 'sneakers_app:index' %}"
                    class="nav-link align-middle px-0"
                  >
                    <i class="fs-4 bi-house"></i>
                    <span
                      id="home"
                      class="ms-1 d-sm-inline text-white display-6"
                      style="font-family: 'Koulen', cursive"
                      >Home</span
                    >
                  </a>
                </li>
                <li>
                  <a
                    href="#submenu1"
                    data-bs-toggle="collapse"
                    class="nav-link px-0 align-middle"
                  >
                    <i class="fs-4 bi-speedometer2"></i>
                    <span
                      class="ms-1 d-sm-inline text-white display-6"
                      style="font-family: 'Koulen', cursive"
                      >Brands</span
                    >
                  </a>
                  <ul
                    class="collapse nav flex-column ms-1"
                    id="submenu1"
                    data-bs-parent="#menu"
                    v-for="brand in brands"
                  >
                    <li class="w-100">
                      <a
                        v-on:click="brandSneaks(brand)"
                        href="#"
                        class="nav-link px-0"
                      >
                        <span
                          class="d-sm-inline"
                          style="font-family: 'Koulen', cursive"
                          >[[brand]]</span
                        >
                      </a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a v-on:click="upcomingSneaks" href="#" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-people"></i>
                    <span
                      class="ms-1 d-sm-inline text-white display-6"
                      style="font-family: 'Koulen', cursive"
                      >Upcoming Sneaks</span
                    >
                  </a>
                  </li>

                <li>
                  <a href="#" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-people"></i>
                    <span
                      class="ms-1 d-sm-inline text-white display-6"
                      style="font-family: 'Koulen', cursive"
                      >Search</span
                    >
                  </a>
                  </li>

                  <input
                    class="form-control-sm"
                    type="text"
                    v-model="search"
                    value="search"
                    placeholder="Search"
                    @keyup.enter="searchSneaks(search)"
                  />
                  <br />
                  <button @click="searchSneaks(search)" class="btn btn-warning">
                    Search
                  </button>
                </li>
              </ul>
              <hr />
              <div class="dropdown pb-4">
                <a
                  href="#"
                  class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                  id="dropdownUser1"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  <img
                    src="{% static 'sneakers_app/images/Sneaks.jpg' %}"
                    alt="hugenerd"
                    width="30"
                    height="30"
                    class="rounded-circle"
                  />
                  <span
                    class="d-none d-sm-inline mx-1"
                    style="font-family: 'Koulen', cursive"
                    >Login</span
                  >
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                  <li><a class="dropdown-item" href="{% url 'sneakers_app:register' %}">Register</a></li>
                  <li>
                  <li>
                    <a
                    
                      class="dropdown-item"
                      href="{% url 'sneakers_app:user_login' %}"
                      >Login</a
                    >
                 
                
                </ul>
              </div>
            </div>
          </div>
          <div class="col text-center">
            <!-- <div id="app" > -->
            <nav
              class="navbar navbar-dark bg-dark fixed-top navbar-custom"
              style="margin-left: 275px"
            >
              <div class="container">
                <li
                  class="navbar-nav text-white mx-auto display-3"
                  style="list-style: none; font-family: 'Koulen', cursive"
                >
                  [[header]]
                </li>
                <a href="" class="navbar-brand">
                  <img
                    class="img-thumbnail img-fluid rounded-circle"
                    style="max-width: 75px"
                    src="{% static 'sneakers_app/images/Sneaks.jpg' %}"
                    alt="brand image"
                  />
                </a>
              </div>
            </nav>

            <section  style="margin-top: 100px">
              <!-- SHOE DISPLAY -->
              <div
                v-for="shoe in shoes"
                class="card d-inline-block"
                style="width: 18rem"
              >
                <img
                  v-if="shoe.image.thumbnail"
                  :src="[[shoe.image.thumbnail]]"
                  class="card-img-top"
                  :alt="[[shoe.silhouette]]"
                />
                <img
                  v-else
                  src="{% static 'sneakers_app/images/INA.jpeg' %}"
                  class="card-img-top"
                  alt="image not available"
                />

                <div class="card-body">
                  <h5 class="card-title">[[shoe.name]]</h5>
                  <p class="card-text">[[shoe.brand]]</p>
                  <p class="card-text">Release Date: [[shoe.releaseDate]]</p>
                  <p class="card-text">Retail Price: $[[shoe.retailPrice]]</p>
                  <a :href="[[shoe.links.flightClub]]" target="_blank"
                    >Flight Club</a
                  ><br />
                  <a :href="[[shoe.links.goat]]" target="_blank">GOAT</a>
                </div>
              </div>
              <!-- END OF SHOE DISPLAY -->
              <nav aria-label="Page navigation" class="mt-5">
                <ul class="pagination justify-content-center">
                  <li class="page-item"><a v-on:click="homeSneaks" class="page-link" href="#">Home</a></li>
                  <li class="page-item"><a v-on:click="previousPage(previous)" class="page-link" href="#">Previous</a></li>
                  <li class="page-item"><a v-on:click="nextPage(next)" class="page-link" href="#">Next</a></li>
                </ul>
              </nav>
            
            <div class="my-5">
              <button class="btn btn-primary">
                <a class="text-white text-decoration-none" href="#home">TOP</a>
              </button>
            </div>

        
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap JavaScript -->
    <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

Sneakers_proj/sneakers_app/templates/sneakers_app/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Koulen&display=swap"
      rel="stylesheet"
    />
    <!-- Link to CSS File -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'sneakers_app/css/style.css' %}"
    />
    <!-- Link to JS File -->
    <script defer src="{% static 'sneakers_app/js/app.js' %}"></script>
    <!-- favicon -->
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'sneakers_app/images/Sneaks.jpg' %}"
    />
    <!-- VUE -->

    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>

    <title>Sneaks</title>
  </head>
  <body>
    <div id="app">
      <div class="container-fluid">
        <div class="row flex-nowrap">
          <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div
              class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
            >
              <ul
                class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
                id="menu"
              >
                <li class="nav-item">
                  <a
                    href="{% url 'sneakers_app:index' %}"
                    class="nav-link align-middle px-0"
                  >
                    <i class="fs-4 bi-house"></i>
                    <span
                      id="home"
                      class="ms-1 d-sm-inline text-white display-6"
                      style="font-family: 'Koulen', cursive"
                      >Home</span
                    >
                  </a>
                </li>
                <li>
                  <a
                    href="#submenu1"
                    data-bs-toggle="collapse"
                    class="nav-link px-0 align-middle"
                  >
                    <i class="fs-4 bi-speedometer2"></i>
                    <span
                      class="ms-1 d-sm-inline text-white display-6"
                      style="font-family: 'Koulen', cursive"
                      >Brands</span
                    >
                  </a>
                  <ul
                    class="collapse nav flex-column ms-1"
                    id="submenu1"
                    data-bs-parent="#menu"
                    v-for="brand in brands"
                  >
                    <li class="w-100">
                      <a
                        v-on:click="brandSneaks(brand)"
                        href="#"
                        class="nav-link px-0"
                      >
                        <span
                          class="d-sm-inline"
                          style="font-family: 'Koulen', cursive"
                          >[[brand]]</span
                        >
                      </a>
                    </li>
                    
                  </ul>
                </li>

                <li>
                  <a href="#" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-people"></i>
                    <span
                      class="ms-1 d-sm-inline text-white display-6"
                      style="font-family: 'Koulen', cursive"
                      >Search</span
                    >
                  </a>
                  </li>

                  <input
                    class="form-control-sm"
                    type="text"
                    v-model="search"
                    value="search"
                    placeholder="Search"
                    @keyup.enter="searchSneaks(search)"
                  />
                  <br />
                  <button  @click="searchSneaks(search)" class="btn btn-warning">
                    Search
                  </button>
                </li>
              </ul>
              <hr />
              <div class="dropdown pb-4">
                <a
                  href="#"
                  class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                  id="dropdownUser1"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  <img
                    src="{% static 'sneakers_app/images/Sneaks.jpg' %}"
                    alt="hugenerd"
                    width="30"
                    height="30"
                    class="rounded-circle"
                  />
                  <span
                    class="d-none d-sm-inline mx-1"
                    style="font-family: 'Koulen', cursive"
                    >Login</span
                  >
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                  <li><a class="dropdown-item" href="{% url 'sneakers_app:register' %}">Register</a></li>
                  <li>
                  <li>
                    <a
                    href="{% url 'sneakers_app:user_login' %}"
                      class="dropdown-item"
                      
                      >Login</a
                    >
                  </li>
                  <li><a class="dropdown-item" href="#">Profile</a></li>
                  <li>
                    <hr class="dropdown-divider" />
                  </li>
                  <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div>
            <!-- <div id="app" > -->
            <nav
              class="navbar navbar-dark bg-dark fixed-top navbar-custom"
              style="margin-left: 275px"
            >
              <div class="container">
                <li
                  class="navbar-nav text-white mx-auto display-3"
                  style="list-style: none; font-family: 'Koulen', cursive"
                >
                  [[header]]
                </li>
                <a href="" class="navbar-brand">
                  <img
                    class="img-thumbnail img-fluid rounded-circle"
                    style="max-width: 75px"
                    src="{% static 'sneakers_app/images/Sneaks.jpg' %}"
                    alt="brand image"
                  />
                </a>
              </div>
            </nav>

            <section  style="margin-top: 100px">
             <!-- REGISTER SECTION -->
             <div class="container">
              <div class="shadow bg-body rounded col-6 p-5"
              style="background-color: gray ;">
 
           <h1>Login</h1>
           <br>
              <form action="" method="POST">
               {% csrf_token %}
               {{form2.as_p}}
               <button type="submit" class="btn btn-primary">
                 submit
               </button>
              </form>
            
             </div>
           </div>
    

            <!-- 
  
            <!-- END OF CONTENT AREA -->
          </div>
        </div>
      </div>
    </div>

    

    <!-- Bootstrap JavaScript -->
    <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

Sneakers_proj/sneakers_app/templates/sneakers_app/register.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Koulen&display=swap"
      rel="stylesheet"
    />
    <!-- Link to CSS File -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'sneakers_app/css/style.css' %}"
    />
    <!-- Link to JS File -->
    <script defer src="{% static 'sneakers_app/js/app.js' %}"></script>
    <!-- favicon -->
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'sneakers_app/images/Sneaks.jpg' %}"
    />
    <!-- VUE -->

    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>

    <title>Sneaks</title>
  </head>
  <body>
    <div id="app">
      <div class="container-fluid">
        <div class="row flex-nowrap">
          <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div
              class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
            >
              <ul
                class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
                id="menu"
              >
                <li class="nav-item">
                  <a
                    href="{% url 'sneakers_app:index' %}"
                    class="nav-link align-middle px-0"
                  >
                    <i class="fs-4 bi-house"></i>
                    <span
                      id="home"
                      class="ms-1 d-sm-inline text-white display-6"
                      style="font-family: 'Koulen', cursive"
                      >Home</span
                    >
                  </a>
                </li>
                <li>
                  <a
                    href="#submenu1"
                    data-bs-toggle="collapse"
                    class="nav-link px-0 align-middle"
                  >
                    <i class="fs-4 bi-speedometer2"></i>
                    <span
                      class="ms-1 d-sm-inline text-white display-6"
                      style="font-family: 'Koulen', cursive"
                      >Brands</span
                    >
                  </a>
                  <ul
                    class="collapse nav flex-column ms-1"
                    id="submenu1"
                    data-bs-parent="#menu"
                    v-for="brand in brands"
                  >
                    <li class="w-100">
                      <a
                        v-on:click="brandSneaks(brand)"
                        href="#"
                        class="nav-link px-0"
                      >
                        <span
                          class="d-sm-inline"
                          style="font-family: 'Koulen', cursive"
                          >[[brand]]</span
                        >
                      </a>
                    </li>
                  </ul>
                </li>

                <li>
                  <a href="#" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-people"></i>
                    <span
                      class="ms-1 d-sm-inline text-white display-6"
                      style="font-family: 'Koulen', cursive"
                      >Search</span
                    >
                  </a>
                  </li>

                  <input
                    class="form-control-sm"
                    type="text"
                    v-model="search"
                    value="search"
                    placeholder="Search"
                    @keyup.enter="searchSneaks(search)"
                  />
                  <br />
                  <button @click="searchSneaks(search)" class="btn btn-warning">
                    Search
                  </button>
                </li>
              </ul>
              <hr />
              <div class="dropdown pb-4">
                <a
                  href="#"
                  class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                  id="dropdownUser1"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  <img
                    src="{% static 'sneakers_app/images/Sneaks.jpg' %}"
                    alt="hugenerd"
                    width="30"
                    height="30"
                    class="rounded-circle"
                  />
                  <span
                    class="d-none d-sm-inline mx-1"
                    style="font-family: 'Koulen', cursive"
                    >Login</span
                  >
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                  <li><a class="dropdown-item" href="{% url 'sneakers_app:register' %}">Register</a></li>
                  <li>
                  <li>
                    <a
                    
                      class="dropdown-item"
                      href="{% url 'sneakers_app:user_login' %}"
                      >Login</a
                    >
                  </li>
                  <li><a class="dropdown-item" href="#">Profile</a></li>
                  <li>
                    <hr class="dropdown-divider" />
                  </li>
                  <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div>
            <!-- <div id="app" > -->
            <nav
              class="navbar navbar-dark bg-dark fixed-top navbar-custom"
              style="margin-left: 275px"
            >
              <div class="container">
                <li
                  class="navbar-nav text-white mx-auto display-3"
                  style="list-style: none; font-family: 'Koulen', cursive"
                >
                  [[header]]
                </li>
                <a href="" class="navbar-brand">
                  <img
                    class="img-thumbnail img-fluid rounded-circle"
                    style="max-width: 75px"
                    src="{% static 'sneakers_app/images/Sneaks.jpg' %}"
                    alt="brand image"
                  />
                </a>
              </div>
            </nav>

            <section  style="margin-top: 100px">
             <!-- REGISTER SECTION -->
             <div class="container">
             <div class="shadow bg-body rounded col-6 p-5"
             style="background-color: gray ;">

          <h1>Register</h1>
          <br>
             <form action="" method="POST">
              {% csrf_token %}
              {{form.as_p}}
              <button type="submit" class="btn btn-primary">
                submit
              </button>
             </form>
           
            </div>
          </div>
          

            <!-- 
  
            <!-- END OF CONTENT AREA -->
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap JavaScript -->
    <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>